// @flow

export const LOAD_DATA_REQUEST = 'LOAD_DATA_REQUEST';
export const CHANGE_ACTIVE_TAB = 'CHANGE_ACTIVE_TAB';
export const ADD_COUNTRY_TO_COMPARISON = 'ADD_COUNTRY_TO_COMPARISON';
export const REMOVE_COUNTRY_FROM_COMPARISON = 'REMOVE_COUNTRY_FROM_COMPARISON';
export const CLEAR_COMPARISON_LIST = 'CLEAR_COMPARISON_LIST';
export const UPDATE_CHART_THRESHOLD = 'UPDATE_CHART_THRESHOLD';
